### ISSUE TITLE
In Windows OS, terminal hangs if I try to show a sampleset a second time

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-inspector#104]
If I try from a CMD terminal of a Win 10 OS running iPython to use ``dwave.inspector.show(sampleset)`` twice, the second attempt causes the terminal to hang and it needs to be closed (CNTR-C and closing the browser window do not end the task). 
This happens for both Pegasus and Chimera graphs. 
Brower: Chrome version Version 88.0.4324.182 (Official Build) (64-bit)

**Comment by randomir** [comment]
Verified. It happens on Linux as well.
