### ISSUE TITLE
Inspector fails to load giving "Error: Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by ozlemsalehi** [dwavesystems/dwave-inspector#106]
I am using Windows 10 and Chrome Browser. 

When I call `dwave.inspector.show(sampleset)` from the Jupyter Notebook, I am getting the error 

"Error: Unexpected token < in JSON at position 0".

**Comment by randomir** [comment]
Can you please provide additional details to help us reproduce this problem:
- are you using JupyterLab, or something else?
- do you run it natively, or in a (docker) container, VM, etc?
- what's your python version?
- pip/conda?
- what's your ocean version, alternatively, dwave-inspector version?

Thanks!

**Comment by ozlemsalehi** [comment]
- I am using Jupyter Notebook 5.7.8
- I run it directly from Windows
- Phyton version 3.7.3
- conda 4.10.0 pip 21.0.1
- Dwave Cloud Client:  0.8.1 Dwave-inspector 0.2.5

Thank you.

**Comment by ozlemsalehi** [comment]
It does not always happen by the way but I don't have an idea why it happens. When this happens, I have to restart the kernel as otherwise the cell is stuck running.

**Comment by randomir** [comment]
That's helpful. Can you correlate failures with the problem you're inspecting, or other changes in env?

**Comment by randomir** [comment]
Hey @ozlemsalehi, would you happen to have numpy types included in the sampled bqm, by any chance? See #127.

**Comment by ozlemsalehi** [comment]
Nope, this was not the case.

**Comment by randomir** [comment]
Thank you!

Would you be able to share a minimal code sample that reproduces this issue?

**Comment by randomir** [comment]
Fixed with #81.
