### ISSUE TITLE
Add support for Jupyter notebook

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwave-inspector#109]
Currently, we open the inspector app in a browser window.

To support `dwave.inspector.show()` from a Jupyter notebook, we need to display the inspector app inline.

**Comment by randomir** [comment]
Hi @ccalaza,

This is becoming a popular feature request, it seems. We'll prioritize it. Thanks!

Currently I can't think of a workaround for your use case. Long term, something like #132 would help, but that's not available yet.

**Comment by ccalaza** [comment]
Hi @randomir,

is there any progress getting the inpector to display inline? We have been getting more requests from our JUNIQ users to make the inspector available through our portal. 

Do you know how this is done in Leap for example? Maybe we could implement sth similar on our side.

X
Carlos

**Comment by randomir** [comment]
Hey @ccalaza, thank you for pointing out the significance of this feature to you. We started working on it, and the support for the Inspector in _local Jupyter notebooks_, including environments like _VSCode_ should be available within a week.

However, your use case is a bit more specific. It's similar to Leap IDE, but specific to your JUNIQ-Cloud.

In Leap IDE, the inspector interface is served from within the workspace, bound to workspace's container `localhost`. However, we expose that port via proxy on an externally available https endpoint -- which then in turn can be accessed from user's machine (UA). Do you have a similar mechanism in place in your JUNIQ-Cloud that could be leveraged?

**Comment by ccalaza** [comment]
Hi @radomir!

Yes, we do have such a mechanism. We have just figured out earlier today that we are missing this url translation for the inspector to work behind a http-configurable proxy like the one we have at JUNIQ. 

In our case we translate the url like this:
https://jupyter-server-proxy.readthedocs.io/en/latest/arbitrary-ports-hosts.html#with-jupyterhub

**Comment by randomir** [comment]
Hey @ccalaza, that sounds great because it's not specific to your environment -- I can build in the support for it, if you'd like. Or you prefer to do it yourselves?

**Comment by ccalaza** [comment]
It would be great if you could add this feature, otherwise I think we would need to maintain a modified version of the inspector from now on and this could end up being problematic...

**Comment by randomir** [comment]
@ccalaza, local Jupyter support is added in #140 (please feel free to test it!), and proxy support will be implemented with #141.
