### ISSUE TITLE
update readme - mention Advantage  as example of structured solver rather than D-Wave 2000Q

### ISSUE THREAD

**Issue by fionahanington** [dwavesystems/dwave-inspector#136]
update readme - mention Advantage(TM) as example of structured solver rather than D-Wave 2000Q

A tool for visualizing problems submitted to, and answers received from, a D-Wave structured solver such as a D-Wave 2000Q quantum computer. > A tool for visualizing problems submitted to, and answers received from, a D-Wave structured solver such as an Advantage^TM quantum computer.

**Comment by randomir** [comment]
FWIW, the example will use Advantage by default.
