### ISSUE TITLE
Introduce a mechanism for URL rewriting before viewing

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwave-inspector#141]
Sometimes the inspector server runs on host A, but is exposed (proxied) as host B, which is then made available to the user (while A might not be).

To support this use case we can introduce a framework of pluggable URL rewriters, similarly to what we do with viewers. A URL rewriter would be called just before the call to `view()`, or as part of it.

For a motivating example, see https://github.com/dwavesystems/dwave-inspector/issues/109#issuecomment-1326805731.

**Comment by randomir** [comment]
Looking at the [docs linked](https://jupyter-server-proxy.readthedocs.io/en/latest/arbitrary-ports-hosts.html) seems like the final address can be known server side beforehand. It should be something like the below, no?
```
<public-base>/<notebook-path>/proxy/<port>
```

**Comment by jhgoebbert** [comment]
No, this is just for direct access to the port.  
But in general one wants to write (based on jupyter-server-proxy) a special jupyter-dwave-proxy which would add a launch button on the launch panel like it is documented here:  
https://jupyter-server-proxy.readthedocs.io/en/latest/launchers.html#jupyterlab-launcher-extension
Launcher examples:
- https://github.com/topics/jupyter-server-proxy  

The URL of a Xpra launched with the launcher-extension https://github.com/FZJ-JSC/jupyter-xprahtml5-proxy would be for example something like:
https://jupyter-jsc.fz-juelich.de/user/jonexample/p98343822a9043cba2fe4a62e735347c/xprahtml5/index.html?username=jovyan&password=90OmXssgt62zy5QI&encryption=AES&key=6j0p7AD6IDj5eZKo&sharing=true

**Comment by randomir** [comment]
@jhgoebbert, I'm not familiar with your setup, but to render the Inspector inline in a Jupyter notebook, all one needs (if it runs JHub/JLab through reverse proxy) is support for `jupyter-server-proxy`. We'll add that in #144.

Please correct me if I'm wrong.

**Comment by jhgoebbert** [comment]
Great, this is fantastic! Thank you for your work and the code update!  
We are building our new software stage right now and will try to enable it for all users there. This really makes a big difference.

**Comment by randomir** [comment]
For usage example, see https://github.com/dwavesystems/dwave-inspector/issues/144#issuecomment-1363822008.
