### ISSUE TITLE
Add the `PROBLEM_TIMING_DATA` solver properties

### ISSUE THREAD

**Issue by mdecandia** [dwavesystems/dwave-inspector#169]
to help with QPU runtime estimation and ensure that users can see all the solver properties that are available to them. 
The property could be rendered similarly to how it is rendered in the Leap Solver Details modal:
![Screen Shot 2024-01-15 at 15 57 51 PM](https://github.com/dwavesystems/dwave-inspector/assets/7495207/24b921eb-d21c-4dbf-9635-f10cad29bdb8)
![Screen Shot 2024-01-15 at 15 58 05 PM](https://github.com/dwavesystems/dwave-inspector/assets/7495207/f4a4c10b-408d-4713-a2ab-3d4acd7132b1)

**Comment by randomir** [comment]
Docs for [`problem_timing_data`](https://docs.dwavesys.com/docs/latest/c_solver_properties.html#problem-timing-data).

**Comment by randomir** [comment]
@mdecandia, @fionahanington, I'm not convinced we should add all these parameters to the inspector UI. It's 14 new parameters (we currently have 24 displayed), the value of which is questionable for human consumption.

Wasn't this solver property added mainly for programmatic use, like QPU access time estimation?

Have in mind we currently don't render "big" properties like `qubits`, `couplers` and `anneal_offset_ranges`.

**Comment by mdecandia** [comment]
That makes sense. I don't think it's a must. I'll close this issue.
